include:
  - ./airflow/docker-compose.yml

services:

  rabbitmq:
    image: rabbitmq:3.12-management
    hostname: rabbitmq
    ports: 
      - 15672:15672
      - 5672:5672

  minio:
    image: minio/minio:RELEASE.2023-11-06T22-26-08Z
    command: server /data --console-address ":9001"
    ports:
      - 9000:9000
      - 9001:9001

  rabbit-to-minio:
    build:
      context: .
      dockerfile: Dockerfile
    image: rabbit-to-minio

  mongo:
      image: mongo
      container_name: projet-persistence
      ports:
        - "27017:27017"
      restart: always
      environment:
        MONGO_INITDB_ROOT_USERNAME: test
        MONGO_INITDB_ROOT_PASSWORD: password

  rabbit-to-mongodb:
    build:
      context: .
      dockerfile: DockerFileMongoDb
    image: rabbit-to-mongodb
    